# Boost Bluetooth TX power to max
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Use newer Bluetooth connection parameters (in theory for a more stable split connection)
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable the keyboard to be recognized in more BIOS's, but this will conflict with N key rollover (which is a more modern feature, but that fortunately is not used in this keyboard config anywhere)
CONFIG_ZMK_USB_BOOT=y